### PR TITLE
Stripe lib updated to 7, Stripe Checkout & webhook & some new attributes 

### PR DESCRIPTION
**Pull request by raimon-segura**
Hi Igor!

I've updated the stipe library, composer.json , from version 4 to 7, the latest one. Also, I've updated its test. Beside this, I've added the checkout UI & Stripe's session for an easy & quick payment gateway. 

The webhook creates a subscriptions if its created with "Stripe checkout UI" , also you can refresh/load subscriptions from stripe's api.

Hope it works for you! ...Let me how it looks

Thanks!

raimon.

### CODE REVIEW

**Comment by raimon-segura** [comment]
https://travis-ci.org/yii2mod/yii2-cashier/builds/625800603?utm_source=github_status&utm_medium=notification

it shows a api key error:
Stripe\Exception\AuthenticationException: No API key provided.  (HINT: set your API key using "Stripe::setApiKey(<API-KEY>)".  You can generate API keys from the Stripe web interface.  See https://stripe.com/api for details, or email support@stripe.com if you have any questions.

How do you test those cases? ..I've seen in your test results ans 

Setting environment variables from repository settings
$ export STRIPE_SECRET=[secure]

**Comment by igor-chepurnoi** [comment]
Hi @raimon-segura, thanks a lot for your PR. I'll check it today and I hope I'll merge it

**Comment by igor-chepurnoi** [comment]
But, this package is very similar to the laravel cashier package. I think we should check the last changes in that one

**Comment by raimon-segura** [comment]
Hi!... thanks for your quick reply!

that's true, lavarel one has more functions than yii2 version... I'll take a look.

Although, lavarel package seems that doesn't have any "stripe checkout" widget nor metada optional data.
The main changes are:
- new stripe checkout widget 
- webhook controller to support stripe checkout 
- subscriptionBuilder to support subscription refresh.
- 3 new attributes
- stripe version 7 compatibility fixes

Besides this, if you merge these changes you will need to "release" a new version, right?

Do you have any guideline to fix travis errors about stripe key?

Many Thanks!

**Comment by igor-chepurnoi** [comment]
@raimon-segura I'll check laravel version first and then I'll let you know

**Comment by raimon-segura** [comment]
Hi Igor!,

I've added few changes.. I'm thinking to add another column(current_period_end) to keep when the subscription ends. 

I've tried to use ends_at colum to store "current_period_end" but its a quite rare, because of how is used this field in SubscriptionModel ...So, resume/cancel/create subscription not works as before and I will undo changes about ends_at as soon as posible. 

A null value of  ends_at means that Subscription is NOT cancelled:
SubscriptionModel.php L141:
    public function cancelled(): bool
    {
        return !is_null($this->ends_at);
    }

Because of that, there are 2 test that are failing. lavarel cashier uses ends_at in the same way:
https://github.com/laravel/cashier/issues/353
https://github.com/laravel/cashier/blob/10.0/src/Subscription.php#L196
https://laravel.com/docs/5.3/billing#cancelling-subscriptions

regards!

**Comment by raimon-segura** [comment]
Just updated with new attribute: current_period_end . 
With that current_period_end & cancel_at_period_end you can check the vadility of a subscription & its recurring billing without any stripe request. 

"ends_at" attribute works like lavarel cashier.

let me know  how it looks :D 

Thanks!

**Comment by raimon-segura** [comment]
Hi Igor!,

Hope your are doing well!!

I've just update a couple of things:
1- Added composer-lock.json to have the same dependency versions.
2- Update all composer libs to latest version, nesbot/carbon is deprecated and generates some conflicts with other libs in my yii project.

BTW, all tests are passed in my machine :D ... travis-ci have some issues, do you know why?

Many thanks!

**Comment by paskuale75** [comment]
what is the most updated version? Why was this pull request not loaded? Thanks

**Comment by raimon-segura** [comment]
ive been using a forked version , from my repository, for a few weeks... It
uses an updated version of php and stripe

Regards

**Comment by raimon-segura** [comment]
Beside php & stripe versions, the most important update is "Stripe's
checkout UI". it simplifies a lot the payment process using the stripe UI
that complians all the EU laws.Then in the webhook you can save what
ever you want: subscription, payment, etc... in your database,
Another cool feature is to retrieve all the payments done by user from
stripe remote server, so you always can update your own databases in case
that webhook fails fo whatever reason.

regards!

**Comment by kmindi** [comment]
Is there any progress merging this / updating this awesome library to the recent stripe versions/changes?

**Comment by kmindi** [comment]
btw: symfony requires "PHP 7.2.5 or higher and these PHP extensions (which are installed and enabled by default in most PHP 7 installations): Ctype, iconv, JSON, PCRE, Session, SimpleXML, and Tokenizer;" that's why the build is failing

**Comment by raimon-segura** [comment]
I've been using a forked version in a php 7.3 server, so the tests should work changing the php version in composer.json file.

**Comment by kmindi** [comment]
nice, yet some style fixes are preventing it an the missing api key, see #16

**Pull request merged**
